TeamPiped/Piped-Backend

src/main/java/me/kavin/piped/Main.java

It was always text/plain and HTTP 200 OK even when there was an error. I fixed that.

add status code, mimetype to response

---

.github/workflows/ci.yml

Use OpenJ9 in CI.

---

build.gradle

This should theoretically fix the music video issues.

Temporarily test TiA4f8R's fork.

---

config.properties
src/main/java/me/kavin/piped/consts/Constants.java

Allows configuring an http proxy to use for outbound requests.

Add support for outbound http proxy

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/obj/Channel.java

I noticed subscriber count was missing while looking at the code. If this was intentional then just close this MR.

Add subscriber count to channelResponse

---

.dockerignore
.github/workflows/docker-build-test.yml
api-test.sh

Closes https://github.com/TeamPiped/Piped/issues/599 if it works.

Add script and CI to automatically test backend changes.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Change rss entry from id to link

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/698

Fix feed validation errors

---

config.properties
src/main/java/me/kavin/piped/Main.java
src/main/java/me/kavin/piped/consts/Constants.java

Closes TeamPiped/Piped#771
The default feed retention is 30 days now.

Add feed retention configuration option

---

src/main/java/me/kavin/piped/utils/LbryHelper.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java

Should fix an issue where you find "Comparison method violates its general contract!"

Simplify comparators

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/docker-build-test.yml
.github/workflows/docker-build.yml
.gitignore
Dockerfile
Dockerfile.openj9
src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/consts/Constants.java
testing/api-test.sh

Add route to display version information.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

If the sessionId is invalid, false should be returned for subscribed, we make it the client's responsibility to ensure the sessionId is valid.

Don't perform authentication checks in subscribed route

---

src/main/java/me/kavin/piped/utils/DatabaseHelper.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java

By replacing inner join with a left join.
Closes https://github.com/TeamPiped/Piped/issues/872

Fix for bug where subscriptions can't be fetched on fresh accounts

---

build.gradle
src/main/java/me/kavin/piped/utils/ResponseHelper.java

Related: https://github.com/TeamNewPipe/NewPipeExtractor/pull/807

Update NPE and remove the caching of CommentsInfo instances.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Have I been Pwned seems to allow empty passwords. (???)

Check if username and password is empty during registration.

---

src/main/java/me/kavin/piped/ServerLauncher.java
testing/api-test.sh

Closes https://github.com/TeamPiped/Piped/issues/908

Add check for database session in healthcheck.

---

src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/utils/DatabaseHelper.java
src/main/java/me/kavin/piped/utils/DatabaseSessionFactory.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/obj/db/Playlist.java
src/main/java/me/kavin/piped/utils/obj/db/PlaylistVideo.java
testing/api-test.sh

Closes https://github.com/TeamPiped/Piped/issues/358

Add custom playlists

---

src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/utils/resp/InvalidRequestResponse.java

As types were being confused, and null value would appear as "null"

Handle JSON data better

---

src/main/java/me/kavin/piped/utils/obj/db/Playlist.java

Add index for playlist owner.

---

src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/URLUtils.java

Closes https://github.com/TeamPiped/Piped/issues/1004

Add support for a different address for proxying images

---

src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/utils/DatabaseHelper.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/obj/db/User.java
src/main/java/me/kavin/piped/utils/resp/DeleteUserRequest.java
src/main/java/me/kavin/piped/utils/resp/DeleteUserResponse.java
testing/api-test.sh

I have implemented backend-code for account deletion, and added a test for it in `api-test.sh`.
I have verified that:
- The code can build (via Docker)
- The code can run (via Docker Compose)
- The API test (`api-test.sh`) passes

Feature: Implement account deletion

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

This should make them generate faster too.

Limit RSS feed size to 100 entries

---

src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/DatabaseHelper.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/obj/db/Playlist.java
src/main/java/me/kavin/piped/utils/obj/db/PlaylistVideo.java
src/main/java/me/kavin/piped/utils/obj/db/Video.java
testing/api-test.sh

Add API route to import playlist from YouTube

---

src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java

This would be useful for onion instances.

Allow having a different url for pubsub.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/994

Username length check

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/1073

Case insensitive sort for subscriptions.

---

src/main/java/me/kavin/piped/Main.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java

- Don't use session.getTransaction()
- remove transactions for session.save() calls
- regex to validate channelId for saving channels

Cleanup Transactions.

---

config.properties
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java
src/main/java/me/kavin/piped/utils/RydHelper.java

Closes https://github.com/TeamPiped/Piped/issues/643

Implement RYD-Proxy API implementation

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Reverts TeamPiped/Piped-Backend#308

Revert "Revert distinct from criteria."

---

config.properties
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/LbryHelper.java

Closes https://github.com/TeamPiped/Piped/issues/1237

Add option to disable LBRY.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/1279

Fix authenticated RSS feeds.

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Fix unauthenticated subscriptions where clause

---

config.properties
src/main/java/me/kavin/piped/ServerLauncher.java
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/ResponseHelper.java

see [TeamPiped/Piped#1418](https://github.com/TeamPiped/Piped/pull/1418)

add config for the frontend

---

src/main/java/me/kavin/piped/utils/ResponseHelper.java

Helps with https://github.com/TeamPiped/Piped/issues/1524

Add video count to playlists response.

---

src/main/java/me/kavin/piped/utils/obj/db/Playlist.java

Closes https://github.com/TeamPiped/Piped/issues/1370

Change max length to 200 characters.

---

build.gradle
config.properties
src/main/java/me/kavin/piped/Main.java
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/ExceptionHandler.java

Closes https://github.com/TeamPiped/Piped/issues/1641

Allow using sentry to log errors.

---

src/main/java/me/kavin/piped/server/handlers/ChannelHandlers.java
src/main/java/me/kavin/piped/server/handlers/PlaylistHandlers.java
src/main/java/me/kavin/piped/server/handlers/SearchHandlers.java
src/main/java/me/kavin/piped/server/handlers/StreamHandlers.java
src/main/java/me/kavin/piped/utils/RydHelper.java

And fix potential NPE in RydHelper.

Add some sentry extra data.

---

src/main/java/me/kavin/piped/server/ServerLauncher.java

We will now throw a 400 Bad Request error.

Fix some "NullPointerException: null" errors

---

src/main/java/me/kavin/piped/server/handlers/auth/AuthPlaylistHandlers.java

See https://github.com/TeamPiped/Piped/issues/1762

Implement better playlist querying.

---

src/main/java/me/kavin/piped/utils/DatabaseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/1769

Fix query type error.

---

src/main/java/me/kavin/piped/utils/LbryHelper.java

Closes https://github.com/TeamPiped/Piped/issues/1770

Fix for LBRY domain change.

---

src/main/java/me/kavin/piped/consts/Constants.java

needed for https://github.com/libre-tube/LibreTube/pull/1944

add proxyUrl to `/config`

---

src/main/java/me/kavin/piped/consts/Constants.java

Also see: https://github.com/TeamNewPipe/NewPipeExtractor/pull/983
and https://mastodon.online/@bruvduroiu@mastodon.social/109324895768588973

Add supported countries to frontend properties.

---

src/main/java/me/kavin/piped/server/handlers/auth/AuthPlaylistHandlers.java

closes https://github.com/TeamPiped/Piped/issues/1873

Don't error out when a video of many is private when adding to playlist

---

src/main/java/me/kavin/piped/server/ServerLauncher.java
src/main/java/me/kavin/piped/server/handlers/auth/AuthPlaylistHandlers.java
testing/api-test.sh

Closes TeamPiped/Piped/issues/1952
It's a suggestion to introduce a 'clear playlist' route.

feat: ability to clear a playlist from its videos (#1952)

---

src/main/java/me/kavin/piped/server/handlers/auth/FeedHandlers.java
src/main/java/me/kavin/piped/utils/ChannelHelpers.java

closes https://github.com/TeamPiped/Piped/issues/1415
closes https://github.com/TeamPiped/Piped/issues/1609
closes https://github.com/TeamPiped/Piped/issues/1656
closes https://github.com/TeamPiped/Piped/issues/1328

RSS Feed improvements

---

src/main/java/me/kavin/piped/utils/ChannelHelpers.java

Closes https://github.com/TeamPiped/Piped/issues/1979

Fix escaping URL content that contains special characters.

---

src/main/java/me/kavin/piped/server/handlers/auth/FeedHandlers.java
src/main/java/me/kavin/piped/utils/ChannelHelpers.java

Also, remove exposure to Google's servers for images

Don't escape entire HTML, just the URL.

---

src/main/java/me/kavin/piped/utils/PubSubHelper.java

Closes https://github.com/TeamPiped/Piped/issues/2050

Fix right pubsub url for subscription.

---

build.gradle
config.properties
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/server/ServerLauncher.java
src/main/java/me/kavin/piped/server/handlers/auth/StorageHandlers.java

Required for implementing e2ee sync for Watch History, Preferences, Bookmarks, etc.

Implement persistent client-data storage with S3.

---

src/main/java/me/kavin/piped/utils/CollectionUtils.java
src/main/java/me/kavin/piped/utils/obj/Streams.java

Apparently it's not available for search items which is what I would have liked but it doesn't hurt to have it in Streams either.

Add category for Streams

---

Dockerfile.openj9
Dockerfile.openj9.ci

This should reduce memory usage a bit.
It should be enabled by default already, but I don't think that's working.

Enable -XX:+IdleTuningGcOnIdle

---

.github/workflows/ci.yml
.github/workflows/docker-build-test.yml
.github/workflows/docker-build.yml
Dockerfile
Dockerfile.ci
Dockerfile.openj9
Dockerfile.openj9.ci
build.gradle
src/main/java/me/kavin/piped/utils/Multithreading.java
testing/docker-compose.yugabytedb.yml

And use Virtual threads to reduce CPU usage

Attempt to migrate to Java 19.

---

src/main/java/me/kavin/piped/Main.java

Should fix weird contract violation errors.

Cleanup list randomization code for pubsub.

---

src/main/java/me/kavin/piped/utils/ChannelHelpers.java

Closes https://github.com/TeamPiped/Piped/issues/2251

Fix for channel updates not triggering.

---

src/main/java/me/kavin/piped/server/handlers/auth/FeedHandlers.java
testing/api-test.sh

Closes https://github.com/TeamPiped/Piped/issues/2338

Subscriptions fix

---

.github/workflows/docker-build.yml

Reverts TeamPiped/Piped-Backend#588

Revert "Make openj9 the default latest tag"

---

src/main/java/me/kavin/piped/utils/CustomServletDecorator.java

See https://github.com/TeamPiped/Piped/pull/2471

Allows all methods in CORS.

---

src/main/java/me/kavin/piped/server/handlers/ChannelHandlers.java

Fix for fetching channels without a videos tab.

---

src/main/java/me/kavin/piped/server/handlers/ChannelHandlers.java
src/main/java/me/kavin/piped/utils/DatabaseHelper.java

Closes https://github.com/TeamPiped/Piped/issues/2504

Fix for channels with too large name length.

---

src/main/java/me/kavin/piped/Main.java

Fix failing hard when the database fails to initialize.

---

src/main/java/me/kavin/piped/server/ServerLauncher.java

Should help for finding the cause to https://github.com/TeamPiped/Piped/issues/1730 and https://github.com/TeamPiped/Piped/issues/1130

Add sentry videoId information to pubsub webhook.

---

src/main/java/me/kavin/piped/server/ServerLauncher.java

See https://github.com/TeamPiped/Piped/issues/1130#issuecomment-1581463390

Fix extractor URL for YouTube

---

src/main/java/me/kavin/piped/utils/VideoHelpers.java

Closes https://github.com/TeamPiped/Piped/issues/2519

Fix short content type extraction.

---

src/main/java/me/kavin/piped/server/handlers/StreamHandlers.java
src/main/java/me/kavin/piped/utils/CollectionUtils.java
src/main/java/me/kavin/piped/utils/obj/PipedStream.java

Closes https://github.com/TeamPiped/Piped/issues/2523

Add itags to the streams api.

---

build.gradle
config.properties
src/main/java/me/kavin/piped/Main.java
src/main/java/me/kavin/piped/consts/Constants.java

Should help with https://github.com/TeamPiped/Piped/issues/2487

Add support for setting up a proxy for reqwest.

---

src/main/java/me/kavin/piped/consts/Constants.java

This way we can disable the sign up button in the UI.

add DISABLE_REGISTRATION to frontendProperties

---

src/main/java/me/kavin/piped/server/ServerLauncher.java
src/main/java/me/kavin/piped/utils/SponsorBlockUtils.java

See https://github.com/TeamPiped/Piped/issues/2575

Implement batched fetching of dearrow content.

---

Dockerfile
Dockerfile.azul
Dockerfile.azul.ci
Dockerfile.ci
hotspot-entrypoint.sh

Users can now configure how much ram they want to allocate.

Add common hotspot entrypoint

---

src/main/java/me/kavin/piped/server/handlers/auth/AuthPlaylistHandlers.java

Closes https://github.com/TeamPiped/Piped/issues/2783

Use native SQL queries for removing from playlist.

---

src/main/java/me/kavin/piped/server/handlers/ChannelHandlers.java
src/main/java/me/kavin/piped/utils/DatabaseHelper.java

Also add support for new video handling from channel tabs

Fix channel save new video handling

---

src/main/java/me/kavin/piped/utils/VideoHelpers.java

Otherwise, we will get weird issues such as https://github.com/TeamPiped/Piped/issues/707#issuecomment-1699746906

Fetch page in extractor before using it

---

build.gradle
src/main/java/me/kavin/piped/utils/ChannelHelpers.java

closes https://github.com/TeamPiped/Piped/issues/2130
We could also do this for playlists, but I'm not sure if that's really needed.

feat: support for embeds in the feed rss endpoints

---

.github/workflows/docker-build-test.yml
.github/workflows/docker-build.yml
Dockerfile
Dockerfile.ci

See https://github.com/adoptium/temurin/issues/8

Re-enable eclipse temurin docker builds.

---

build.gradle
config.properties
src/main/java/me/kavin/piped/Main.java
src/main/java/me/kavin/piped/consts/Constants.java
src/main/java/me/kavin/piped/utils/URLUtils.java

See https://github.com/TeamPiped/piped-proxy/pull/116

Implement blake3 proxy query hash

---

src/main/java/me/kavin/piped/server/handlers/auth/FeedHandlers.java
src/main/java/me/kavin/piped/utils/ChannelHelpers.java

closes https://github.com/TeamPiped/Piped/issues/2711

feat: add channel info to rss feed if no videos found

---

build.gradle

closes https://github.com/TeamPiped/Piped/issues/3429

chore(deps): update NewPipeExtractor

---

src/main/java/me/kavin/piped/utils/CollectionUtils.java
src/main/java/me/kavin/piped/utils/obj/Streams.java

closes https://github.com/TeamPiped/Piped/issues/2556

feat: add uploaded timestamp to streams response

---

build.gradle

closes https://github.com/TeamPiped/Piped/issues/3698

chore: bump NPE

---

.github/workflows/docker-build.yml

pin binfmt version in setup qemu action to known-good version to fix docker build

fix docker build github action

---

src/main/java/me/kavin/piped/utils/CollectionUtils.java

Reverts TeamPiped/Piped-Backend#839

chore: revert re-enable srfvp and ump for now

---

src/main/java/me/kavin/piped/utils/URLUtils.java

fix https://github.com/TeamPiped/Piped/issues/4017.

fix crash on empty string query parameters
